#!/usr/bin/env python3
"""Expand common_verbs.json with additional curated EN→KO verb glosses."""

from __future__ import annotations

import json
import re
from pathlib import Path

from nltk.corpus import wordnet as wn

ROOT = Path(__file__).resolve().parent
PATH = ROOT / "common_verbs.json"
WORD_RE = re.compile(r"^[a-z]+(?:-[a-z]+)?$")

# Additional frequent verbs not covered well by Wiktionary alone.
EXTRA: list[tuple[str, str]] = [
    ("abandon", "포기하다"), ("abide", "지키다"), ("abolish", "폐지하다"),
    ("absorb", "흡수하다"), ("abuse", "학대하다"), ("accompany", "동행하다"),
    ("accomplish", "완수하다"), ("account", "설명하다"), ("accumulate", "축적하다"),
    ("accuse", "고발하다"), ("achieve", "이루다"), ("acquire", "획득하다"),
    ("adapt", "적응하다"), ("address", "다루다"), ("adhere", "고수하다"),
    ("adjust", "조정하다"), ("administer", "관리하다"), ("admire", "존경하다"),
    ("admit", "인정하다"), ("adopt", "채택하다"), ("adore", "사랑하다"),
    ("advance", "전진하다"), ("advertise", "광고하다"), ("advise", "충고하다"),
    ("affect", "영향을 미치다"), ("affirm", "단언하다"), ("afford", "여유가 있다"),
    ("age", "나이를 먹다"), ("aid", "돕다"), ("aim", "겨냥하다"),
    ("alarm", "경보하다"), ("alert", "알리다"), ("alienate", "소외시키다"),
    ("allege", "주장하다"), ("allocate", "할당하다"), ("allot", "배당하다"),
    ("alter", "바꾸다"), ("amaze", "놀라게 하다"), ("amend", "개정하다"),
    ("amuse", "즐겁게 하다"), ("analyze", "분석하다"), ("anchor", "고정하다"),
    ("anger", "화나게 하다"), ("animate", "움직이게 하다"), ("annex", "병합하다"),
    ("announce", "알리다"), ("annoy", "짜증나게 하다"), ("anticipate", "예상하다"),
    ("apologize", "사과하다"), ("appeal", "호소하다"), ("applaud", "박수하다"),
    ("apply", "적용하다"), ("appoint", "임명하다"), ("appraise", "평가하다"),
    ("appreciate", "감사하다"), ("approach", "다가가다"), ("approve", "승인하다"),
    ("arbitrate", "중재하다"), ("argue", "논쟁하다"), ("arise", "생기다"),
    ("arm", "무장하다"), ("arouse", "불러일으키다"), ("arrange", "준비하다"),
    ("arrest", "체포하다"), ("arrive", "도착하다"), ("articulate", "분명히 말하다"),
    ("ascend", "오르다"), ("assault", "폭행하다"), ("assemble", "모으다"),
    ("assert", "주장하다"), ("assess", "평가하다"), ("assign", "배정하다"),
    ("assist", "돕다"), ("associate", "연관짓다"), ("assume", "가정하다"),
    ("assure", "보장하다"), ("attach", "붙이다"), ("attack", "공격하다"),
    ("attain", "달성하다"), ("attempt", "시도하다"), ("attend", "참석하다"),
    ("attract", "끌다"), ("attribute", "탓으로 돌리다"), ("audit", "감사하다"),
    ("authorize", "인가하다"), ("automate", "자동화하다"), ("avenge", "복수하다"),
    ("avoid", "피하다"), ("await", "기다리다"), ("awake", "깨우다"),
    ("award", "수여하다"), ("baffle", "당황하게 하다"), ("bake", "굽다"),
    ("balance", "균형 잡다"), ("ban", "금지하다"), ("bandage", "붕대를 감다"),
    ("bang", "쾅 치다"), ("banish", "추방하다"), ("bar", "막다"),
    ("bare", "드러내다"), ("bargain", "흥정하다"), ("bark", "짖다"),
    ("base", "기초하다"), ("bathe", "목욕하다"), ("batter", "세게 치다"),
    ("battle", "싸우다"), ("beam", "환하게 웃다"), ("bear", "견디다"),
    ("befriend", "친구가 되다"), ("beg", "부탁하다"), ("behave", "행동하다"),
    ("behold", "바라보다"), ("belong", "속하다"), ("bend", "구부리다"),
    ("bet", "내기하다"), ("betray", "배신하다"), ("bias", "편향시키다"),
    ("bid", "입찰하다"), ("bill", "청구하다"), ("bind", "묶다"),
    ("bite", "물다"), ("blame", "탓하다"), ("blast", "폭파하다"),
    ("bleed", "피를 흘리다"), ("blend", "섞다"), ("bless", "축복하다"),
    ("blink", "깜빡이다"), ("block", "막다"), ("bloom", "피다"),
    ("blossom", "꽃피다"), ("blow", "불다"), ("bluff", "허세부리다"),
    ("blur", "흐리게 하다"), ("board", "탑승하다"), ("boast", "자랑하다"),
    ("boil", "끓이다"), ("bolt", "빗장을 지르다"), ("bomb", "폭격하다"),
    ("bond", "유대하다"), ("book", "예약하다"), ("boost", "증진하다"),
    ("boot", "부팅하다"), ("border", "접하다"), ("bore", "따분하게 하다"),
    ("borrow", "빌리다"), ("bother", "귀찮게 하다"), ("bounce", "튀다"),
    ("bow", "절하다"), ("box", "권투하다"), ("brace", "받치다"),
    ("brake", "브레이크를 밟다"), ("branch", "갈라지다"), ("brand", "낙인찍다"),
    ("breach", "위반하다"), ("breathe", "숨쉬다"), ("breed", "번식하다"),
    ("bribe", "뇌물을 주다"), ("bridge", "연결하다"), ("brief", "브리핑하다"),
    ("brighten", "밝게 하다"), ("broadcast", "방송하다"), ("browse", "둘러보다"),
    ("brush", "닦다"), ("bubble", "거품이 일다"), ("buckle", "버클을 채우다"),
    ("budget", "예산을 짜다"), ("buffer", "완충하다"), ("bump", "부딪히다"),
    ("bunch", "모으다"), ("bundle", "묶다"), ("burden", "부담을 지우다"),
    ("burn", "타다"), ("burst", "터지다"), ("bury", "묻다"),
    ("butter", "버터를 바르다"), ("button", "단추를 채우다"), ("buzz", "윙윙거리다"),
    ("bypass", "우회하다"), ("calculate", "계산하다"), ("calm", "진정시키다"),
    ("campaign", "캠페인하다"), ("cancel", "취소하다"), ("capture", "포획하다"),
    ("caress", "쓰다듬다"), ("carve", "조각하다"), ("cast", "던지다"),
    ("cater", "제공하다"), ("cause", "일으키다"), ("caution", "주의시키다"),
    ("cease", "멈추다"), ("celebrate", "축하하다"), ("center", "중심에 두다"),
    ("certify", "증명하다"), ("chain", "사슬로 묶다"), ("chair", "사회를 보다"),
    ("challenge", "도전하다"), ("channel", "전달하다"), ("charge", "청구하다"),
    ("charm", "매혹하다"), ("chase", "쫓다"), ("chat", "수다하다"),
    ("cheat", "속이다"), ("cheer", "응원하다"), ("cherish", "아끼다"),
    ("chew", "씹다"), ("chill", "식히다"), ("choke", "질식하다"),
    ("chop", "자르다"), ("chuckle", "킬킬 웃다"), ("circle", "돌다"),
    ("cite", "인용하다"), ("claim", "주장하다"), ("clap", "박수하다"),
    ("clarify", "명확히 하다"), ("clash", "충돌하다"), ("clasp", "꽉 잡다"),
    ("classify", "분류하다"), ("clear", "치우다"), ("click", "클릭하다"),
    ("cling", "달라붙다"), ("clip", "자르다"), ("clothe", "옷을 입히다"),
    ("cloud", "흐리게 하다"), ("clutch", "움켜쥐다"), ("coach", "지도하다"),
    ("coat", "코팅하다"), ("coil", "감다"), ("collapse", "붕괴하다"),
    ("collide", "충돌하다"), ("color", "색칠하다"), ("comb", "빗질하다"),
    ("combat", "싸우다"), ("combine", "결합하다"), ("comfort", "위로하다"),
    ("command", "명령하다"), ("commemorate", "기념하다"), ("commend", "칭찬하다"),
    ("comment", "논평하다"), ("commission", "위임하다"), ("commit", "저지르다"),
    ("communicate", "소통하다"), ("compel", "강요하다"), ("compensate", "보상하다"),
    ("compete", "경쟁하다"), ("compile", "편찬하다"), ("complain", "불평하다"),
    ("complement", "보완하다"), ("complicate", "복잡하게 하다"), ("comply", "따르다"),
    ("compose", "구성하다"), ("compound", "악화시키다"), ("comprehend", "이해하다"),
    ("compress", "압축하다"), ("comprise", "구성하다"), ("compromise", "타협하다"),
    ("compute", "계산하다"), ("conceal", "숨기다"), ("concede", "인정하다"),
    ("conceive", "생각하다"), ("concentrate", "집중하다"), ("conclude", "결론짓다"),
    ("condemn", "비난하다"), ("condense", "응축하다"), ("conduct", "수행하다"),
    ("confer", "협의하다"), ("confess", "고백하다"), ("confide", "털어놓다"),
    ("configure", "구성하다"), ("confine", "가두다"), ("confirm", "확인하다"),
    ("conflict", "충돌하다"), ("conform", "순응하다"), ("confront", "맞서다"),
    ("confuse", "혼란시키다"), ("congratulate", "축하하다"), ("connect", "연결하다"),
    ("conquer", "정복하다"), ("consent", "동의하다"), ("conserve", "보존하다"),
    ("consist", "구성되다"), ("console", "위로하다"), ("consolidate", "통합하다"),
    ("constitute", "구성하다"), ("construct", "건설하다"), ("consult", "상담하다"),
    ("consume", "소비하다"), ("contact", "연락하다"), ("contain", "담다"),
    ("contemplate", "숙고하다"), ("contend", "다투다"), ("contest", "다투다"),
    ("contract", "계약하다"), ("contradict", "모순되다"), ("contrast", "대조하다"),
    ("contribute", "기여하다"), ("control", "통제하다"), ("convene", "소집하다"),
    ("converge", "수렴하다"), ("converse", "대화하다"), ("convert", "전환하다"),
    ("convey", "전달하다"), ("convict", "유죄로 하다"), ("convince", "설득하다"),
    ("cooperate", "협력하다"), ("coordinate", "조정하다"), ("cope", "대처하다"),
    ("copyright", "저작권 등록하다"), ("corner", "궁지에 몰다"), ("correct", "고치다"),
    ("correlate", "상관하다"), ("correspond", "일치하다"), ("corrupt", "타락시키다"),
    ("cough", "기침하다"), ("counsel", "조언하다"), ("counter", "맞서다"),
    ("couple", "결합하다"), ("crack", "금이 가다"), ("craft", "만들다"),
    ("crash", "충돌하다"), ("crawl", "기다"), ("credit", "신용하다"),
    ("creep", "기다"), ("criticize", "비판하다"), ("cross", "건너다"),
    ("crouch", "웅크리다"), ("crowd", "붐비다"), ("crown", "왕관을 씌우다"),
    ("crush", "으깨다"), ("cultivate", "경작하다"), ("cure", "치료하다"),
    ("curl", "말다"), ("curve", "구부러지다"), ("cycle", "순환하다"),
    ("damage", "손상시키다"), ("dampen", "축축하게 하다"), ("dare", "감히 하다"),
    ("darken", "어둡게 하다"), ("dash", "돌진하다"), ("date", "데이트하다"),
    ("dawn", "동이 트다"), ("deal", "다루다"), ("debate", "토론하다"),
    ("decay", "부패하다"), ("deceive", "속이다"), ("declare", "선언하다"),
    ("decline", "거절하다"), ("decorate", "장식하다"), ("decrease", "감소하다"),
    ("dedicate", "헌정하다"), ("deduce", "추론하다"), ("deduct", "공제하다"),
    ("deem", "여기다"), ("deepen", "깊게 하다"), ("defeat", "패배시키다"),
    ("defend", "방어하다"), ("defer", "연기하다"), ("define", "정의하다"),
    ("defy", "거역하다"), ("delay", "지연하다"), ("delete", "삭제하다"),
    ("delight", "기쁘게 하다"), ("deliver", "배달하다"), ("demand", "요구하다"),
    ("demonstrate", "입증하다"), ("denounce", "비난하다"), ("deny", "부인하다"),
    ("depart", "출발하다"), ("depend", "의존하다"), ("depict", "묘사하다"),
    ("deploy", "배치하다"), ("deposit", "예치하다"), ("depress", "우울하게 하다"),
    ("derive", "도출하다"), ("descend", "내려가다"), ("deserve", "받을 만하다"),
    ("design", "설계하다"), ("designate", "지정하다"), ("desire", "원하다"),
    ("despair", "절망하다"), ("destroy", "파괴하다"), ("detach", "분리하다"),
    ("detain", "억류하다"), ("detect", "감지하다"), ("deter", "단념시키다"),
    ("determine", "결정하다"), ("develop", "개발하다"), ("deviate", "벗어나다"),
    ("devise", "고안하다"), ("devote", "바치다"), ("diagnose", "진단하다"),
    ("dictate", "받아쓰게 하다"), ("differ", "다르다"), ("differentiate", "구별하다"),
    ("digest", "소화하다"), ("dilute", "희석하다"), ("dim", "어둡게 하다"),
    ("diminish", "줄어들다"), ("dine", "식사하다"), ("dip", "담그다"),
    ("direct", "지시하다"), ("disable", "비활성화하다"), ("disagree", "반대하다"),
    ("disappear", "사라지다"), ("disappoint", "실망시키다"), ("disapprove", "반대하다"),
    ("discard", "버리다"), ("discharge", "방출하다"), ("discipline", "훈육하다"),
    ("disclose", "공개하다"), ("disconnect", "연결을 끊다"), ("discount", "할인하다"),
    ("discourage", "낙담시키다"), ("discover", "발견하다"), ("discuss", "토론하다"),
    ("disguise", "변장하다"), ("dislike", "싫어하다"), ("dismantle", "해체하다"),
    ("dismiss", "해고하다"), ("dispatch", "파견하다"), ("dispel", "쫓다"),
    ("dispense", "나눠 주다"), ("disperse", "흩어지다"), ("display", "보여 주다"),
    ("dispose", "처분하다"), ("dispute", "논쟁하다"), ("disrupt", "방해하다"),
    ("dissolve", "녹이다"), ("distill", "증류하다"), ("distinguish", "구별하다"),
    ("distort", "왜곡하다"), ("distract", "산만하게 하다"), ("distribute", "배포하다"),
    ("disturb", "방해하다"), ("dive", "잠수하다"), ("diverge", "갈라지다"),
    ("diversify", "다양화하다"), ("divert", "돌리다"), ("divide", "나누다"),
    ("divorce", "이혼하다"), ("document", "기록하다"), ("dodge", "피하다"),
    ("dominate", "지배하다"), ("donate", "기부하다"), ("double", "두 배로 하다"),
    ("doubt", "의심하다"), ("download", "다운로드하다"), ("draft", "초안을 쓰다"),
    ("drag", "끌다"), ("drain", "배수하다"), ("dramatize", "극화하다"),
    ("dread", "두려워하다"), ("dream", "꿈꾸다"), ("dress", "옷을 입다"),
    ("drift", "표류하다"), ("drill", "드릴로 뚫다"), ("drip", "똑똑 떨어지다"),
    ("drop", "떨어뜨리다"), ("drown", "익사하다"), ("dry", "말리다"),
    ("duck", "숙이다"), ("dump", "버리다"), ("duplicate", "복제하다"),
    ("dust", "먼지를 털다"), ("dwell", "살다"), ("dye", "염색하다"),
    ("earn", "벌다"), ("ease", "완화하다"), ("echo", "메아리치다"),
    ("edit", "편집하다"), ("educate", "교육하다"), ("elect", "선출하다"),
    ("elevate", "높이다"), ("elicit", "이끌어 내다"), ("eliminate", "제거하다"),
    ("email", "이메일하다"), ("embark", "착수하다"), ("embed", "삽입하다"),
    ("embody", "구현하다"), ("embrace", "껴안다"), ("emerge", "나타나다"),
    ("emigrate", "이주하다"), ("emit", "방출하다"), ("emphasize", "강조하다"),
    ("employ", "고용하다"), ("empower", "권한을 주다"), ("empty", "비우다"),
    ("enable", "가능하게 하다"), ("enact", "제정하다"), ("encircle", "둘러싸다"),
    ("enclose", "동봉하다"), ("encounter", "마주치다"), ("encourage", "격려하다"),
    ("end", "끝내다"), ("endanger", "위태롭게 하다"), ("endorse", "지지하다"),
    ("endure", "견디다"), ("enforce", "시행하다"), ("engage", "참여하다"),
    ("enhance", "향상하다"), ("enjoy", "즐기다"), ("enlarge", "확대하다"),
    ("enlighten", "계몽하다"), ("enlist", "입대하다"), ("enrich", "풍부하게 하다"),
    ("enroll", "등록하다"), ("ensure", "보장하다"), ("entail", "수반하다"),
    ("enter", "들어가다"), ("entertain", "즐겁게 하다"), ("entice", "유혹하다"),
    ("entitle", "자격을 주다"), ("entrust", "맡기다"), ("envelop", "감싸다"),
    ("envy", "부러워하다"), ("equip", "장비하다"), ("erase", "지우다"),
    ("erect", "세우다"), ("erode", "침식하다"), ("erupt", "분출하다"),
    ("escalate", "확대하다"), ("escape", "탈출하다"), ("escort", "호위하다"),
    ("establish", "설립하다"), ("estimate", "추정하다"), ("etch", "새기다"),
    ("evacuate", "대피하다"), ("evaluate", "평가하다"), ("evaporate", "증발하다"),
    ("evade", "피하다"), ("evoke", "불러일으키다"), ("evolve", "진화하다"),
    ("exaggerate", "과장하다"), ("examine", "조사하다"), ("exceed", "초과하다"),
    ("exchange", "교환하다"), ("excite", "흥분시키다"), ("exclaim", "외치다"),
    ("exclude", "제외하다"), ("excuse", "용서하다"), ("execute", "실행하다"),
    ("exercise", "운동하다"), ("exert", "발휘하다"), ("exhaust", "지치게 하다"),
    ("exhibit", "전시하다"), ("exile", "추방하다"), ("exist", "존재하다"),
    ("exit", "나가다"), ("expand", "확장하다"), ("expect", "기대하다"),
    ("expel", "추방하다"), ("expend", "지출하다"), ("experience", "경험하다"),
    ("experiment", "실험하다"), ("expire", "만료되다"), ("explain", "설명하다"),
    ("explode", "폭발하다"), ("exploit", "이용하다"), ("explore", "탐험하다"),
    ("export", "수출하다"), ("expose", "노출하다"), ("express", "표현하다"),
    ("extend", "연장하다"), ("extract", "추출하다"), ("fabricate", "조작하다"),
    ("facilitate", "용이하게 하다"), ("fade", "바래다"), ("fail", "실패하다"),
    ("faint", "기절하다"), ("fake", "위조하다"), ("falsify", "위조하다"),
    ("falter", "비틀거리다"), ("familiarize", "익숙해지다"), ("fan", "부채질하다"),
    ("fancy", "좋아하다"), ("farm", "경작하다"), ("fascinate", "매혹하다"),
    ("fashion", "만들다"), ("fasten", "고정하다"), ("fathom", "헤아리다"),
    ("favor", "편들다"), ("fax", "팩스하다"), ("fear", "두려워하다"),
    ("feature", "특징으로 하다"), ("feed", "먹이다"), ("feign", "가장하다"),
    ("fell", "쓰러뜨리다"), ("fence", "울타리를 치다"), ("fend", "막아내다"),
    ("ferment", "발효하다"), ("ferry", "나르다"), ("fertilize", "비료를 주다"),
    ("fetch", "가져오다"), ("figure", "생각하다"), ("file", "제출하다"),
    ("fill", "채우다"), ("film", "촬영하다"), ("filter", "거르다"),
    ("finance", "자금을 대다"), ("fine", "벌금을 부과하다"), ("finish", "끝내다"),
    ("fire", "발사하다"), ("fish", "낚시하다"), ("fit", "맞다"),
    ("fix", "고치다"), ("flag", "표시하다"), ("flame", "불타다"),
    ("flap", "퍼덕이다"), ("flare", "번쩍이다"), ("flash", "번쩍이다"),
    ("flatten", "납작하게 하다"), ("flatter", "아첨하다"), ("flee", "도망치다"),
    ("flex", "구부리다"), ("flick", "튕기다"), ("flicker", "깜빡이다"),
    ("flinch", "움찔하다"), ("fling", "내던지다"), ("flip", "뒤집다"),
    ("flirt", "추파를 던지다"), ("float", "뜨다"), ("flock", "모이다"),
    ("flood", "범람하다"), ("flop", "실패하다"), ("flourish", "번성하다"),
    ("flow", "흐르다"), ("flower", "꽃이 피다"), ("fluctuate", "변동하다"),
    ("flush", "붉어지다"), ("flutter", "펄럭이다"), ("foam", "거품이 일다"),
    ("focus", "집중하다"), ("fold", "접다"), ("fool", "속이다"),
    ("forbid", "금지하다"), ("force", "강요하다"), ("forecast", "예보하다"),
    ("foresee", "예견하다"), ("forge", "위조하다"), ("forget", "잊다"),
    ("forgive", "용서하다"), ("fork", "갈라지다"), ("form", "형성하다"),
    ("formalize", "공식화하다"), ("format", "형식화하다"), ("formulate", "공식화하다"),
    ("forsake", "버리다"), ("fortify", "강화하다"), ("forward", "전달하다"),
    ("foster", "촉진하다"), ("foul", "더럽히다"), ("found", "설립하다"),
    ("fracture", "골절하다"), ("fragment", "조각내다"), ("frame", "액자에 넣다"),
    ("free", "풀어 주다"), ("freeze", "얼리다"), ("frequent", "자주 방문하다"),
    ("freshen", "상쾌하게 하다"), ("frighten", "겁주다"), ("frown", "찌푸리다"),
    ("frustrate", "좌절시키다"), ("fry", "튀기다"), ("fuel", "연료를 공급하다"),
    ("fulfill", "이행하다"), ("fumble", "더듬다"), ("function", "기능하다"),
    ("fund", "자금을 대다"), ("furnish", "비치하다"), ("fuse", "융합하다"),
    ("fuss", "법석을 떨다"), ("gain", "얻다"), ("gallop", "질주하다"),
    ("gamble", "도박하다"), ("gather", "모으다"), ("gauge", "측정하다"),
    ("gaze", "바라보다"), ("gear", "준비하다"), ("generalize", "일반화하다"),
    ("generate", "생성하다"), ("gesture", "몸짓하다"), ("giggle", "낄낄 웃다"),
    ("glance", "흘긋 보다"), ("glare", "노려보다"), ("glide", "활공하다"),
    ("glimpse", "언뜻 보다"), ("glisten", "반짝이다"), ("glitter", "반짝이다"),
    ("glorify", "찬양하다"), ("glow", "빛나다"), ("glue", "붙이다"),
    ("govern", "통치하다"), ("grab", "움켜쥐다"), ("grade", "채점하다"),
    ("graduate", "졸업하다"), ("grant", "부여하다"), ("grasp", "움켜쥐다"),
    ("grate", "갈다"), ("gratify", "만족시키다"), ("graze", "풀을 뜯다"),
    ("grease", "기름칠하다"), ("greet", "인사하다"), ("grieve", "슬퍼하다"),
    ("grill", "굽다"), ("grin", "씩 웃다"), ("grind", "갈다"),
    ("grip", "움켜쥐다"), ("groan", "신음하다"), ("groom", "손질하다"),
    ("grope", "더듬다"), ("group", "묶다"), ("growl", "으르렁거리다"),
    ("grumble", "투덜거리다"), ("guarantee", "보장하다"), ("guard", "지키다"),
    ("guess", "추측하다"), ("guide", "안내하다"), ("gulp", "벌컥 마시다"),
    ("gush", "분출하다"), ("hail", "환호하다"), ("halt", "멈추다"),
    ("halve", "반으로 줄이다"), ("hammer", "망치질하다"), ("hand", "건네다"),
    ("handle", "다루다"), ("harass", "괴롭히다"), ("harbor", "품다"),
    ("harden", "단단하게 하다"), ("harm", "해치다"), ("harmonize", "조화시키다"),
    ("harness", "활용하다"), ("harvest", "수확하다"), ("hassle", "귀찮게 하다"),
    ("hasten", "서두르다"), ("hatch", "부화하다"), ("hate", "싫어하다"),
    ("haul", "끌다"), ("haunt", "괴롭히다"), ("heal", "낫다"),
    ("heap", "쌓다"), ("heat", "가열하다"), ("heave", "들어 올리다"),
    ("hedge", "울타리를 치다"), ("heed", "유의하다"), ("heighten", "높이다"),
    ("hesitate", "망설이다"), ("hibernate", "동면하다"), ("hide", "숨다"),
    ("highlight", "강조하다"), ("hike", "하이킹하다"), ("hinder", "방해하다"),
    ("hint", "암시하다"), ("hire", "고용하다"), ("hiss", "쉿 소리를 내다"),
    ("hitch", "걸다"), ("hoard", "비축하다"), ("hobble", "절뚝거리다"),
    ("honor", "존경하다"), ("hook", "걸다"), ("hoot", "부엉거리다"),
    ("hop", "깡충 뛰다"), ("hope", "희망하다"), ("horrify", "겁주다"),
    ("host", "주최하다"), ("house", "수용하다"), ("hover", "맴돌다"),
    ("howl", "울부짖다"), ("hug", "껴안다"), ("hum", "흥얼거리다"),
    ("humble", "겸손하게 하다"), ("humiliate", "모욕하다"), ("hunt", "사냥하다"),
    ("hurl", "내던지다"), ("hurry", "서두르다"), ("hurt", "다치게 하다"),
    ("hush", "조용히 하다"), ("hustle", "서두르다"), ("hydrate", "수분을 공급하다"),
    ("hypothesize", "가설을 세우다"), ("idealize", "이상화하다"), ("identify", "확인하다"),
    ("idle", "게으름 피우다"), ("ignite", "점화하다"), ("ignore", "무시하다"),
    ("illuminate", "비추다"), ("illustrate", "설명하다"), ("imagine", "상상하다"),
    ("imitate", "모방하다"), ("immerse", "담그다"), ("immigrate", "이민하다"),
    ("impair", "손상시키다"), ("impart", "전달하다"), ("impeach", "탄핵하다"),
    ("impede", "방해하다"), ("impel", "재촉하다"), ("implement", "시행하다"),
    ("implicate", "연루시키다"), ("implore", "간청하다"), ("imply", "암시하다"),
    ("import", "수입하다"), ("impose", "부과하다"), ("impress", "감명을 주다"),
    ("imprint", "각인하다"), ("imprison", "투옥하다"), ("improve", "개선하다"),
    ("improvise", "즉흥으로 하다"), ("inaugurate", "취임시키다"), ("incite", "선동하다"),
    ("incline", "기울다"), ("include", "포함하다"), ("incorporate", "포함하다"),
    ("increase", "증가하다"), ("incur", "초래하다"), ("indicate", "나타내다"),
    ("indict", "기소하다"), ("induce", "유도하다"), ("indulge", "탐닉하다"),
    ("infect", "감염시키다"), ("infer", "추론하다"), ("inflate", "부풀리다"),
    ("inflict", "가하다"), ("influence", "영향을 미치다"), ("inform", "알리다"),
    ("infringe", "침해하다"), ("infuriate", "격분시키다"), ("infuse", "주입하다"),
    ("ingest", "섭취하다"), ("inhabit", "거주하다"), ("inhale", "들이마시다"),
    ("inherit", "상속하다"), ("inhibit", "억제하다"), ("initiate", "개시하다"),
    ("inject", "주사하다"), ("injure", "다치게 하다"), ("innovate", "혁신하다"),
    ("inquire", "문의하다"), ("inscribe", "새기다"), ("insert", "삽입하다"),
    ("insist", "주장하다"), ("inspect", "점검하다"), ("inspire", "영감을 주다"),
    ("install", "설치하다"), ("institute", "제정하다"), ("instruct", "지시하다"),
    ("insulate", "절연하다"), ("insult", "모욕하다"), ("insure", "보험에 들다"),
    ("integrate", "통합하다"), ("intend", "의도하다"), ("intensify", "강화하다"),
    ("interact", "상호작용하다"), ("intercept", "가로채다"), ("interfere", "간섭하다"),
    ("interpret", "해석하다"), ("interrupt", "방해하다"), ("intersect", "교차하다"),
    ("intervene", "개입하다"), ("interview", "면접하다"), ("intimidate", "위협하다"),
    ("introduce", "소개하다"), ("invade", "침략하다"), ("invent", "발명하다"),
    ("invert", "뒤집다"), ("invest", "투자하다"), ("investigate", "조사하다"),
    ("invite", "초대하다"), ("invoke", "발동하다"), ("involve", "포함하다"),
    ("iron", "다림질하다"), ("irritate", "자극하다"), ("isolate", "격리하다"),
    ("issue", "발행하다"), ("itch", "가렵다"), ("jab", "쿡 찌르다"),
    ("jail", "투옥하다"), ("jam", "막히다"), ("jeer", "야유하다"),
    ("jerk", "갑자기 움직이다"), ("jest", "농담하다"), ("jog", "조깅하다"),
    ("join", "가입하다"), ("joke", "농담하다"), ("jolt", "흔들다"),
    ("jostle", "밀치다"), ("journey", "여행하다"), ("judge", "판단하다"),
    ("juggle", "저글링하다"), ("jump", "점프하다"), ("justify", "정당화하다"),
    ("kneel", "무릎 꿇다"), ("knit", "뜨다"), ("knock", "두드리다"),
    ("knot", "매듭짓다"), ("know", "알다"), ("label", "라벨을 붙이다"),
    ("lack", "부족하다"), ("ladder", "사다리를 오르다"), ("lag", "뒤처지다"),
    ("lament", "한탄하다"), ("land", "착륙하다"), ("landscape", "조경하다"),
    ("lapse", "만료되다"), ("lash", "채찍질하다"), ("last", "지속하다"),
    ("latch", "걸쇠를 걸다"), ("laugh", "웃다"), ("launch", "시작하다"),
    ("launder", "세탁하다"), ("lay", "놓다"), ("layer", "겹겹이 쌓다"),
    ("lead", "이끌다"), ("leak", "새다"), ("lean", "기대다"),
    ("leap", "뛰어오르다"), ("learn", "배우다"), ("lease", "임대하다"),
    ("leave", "떠나다"), ("lecture", "강의하다"), ("lend", "빌려 주다"),
    ("lengthen", "늘이다"), ("lessen", "줄이다"), ("let", "허락하다"),
    ("level", "평평하게 하다"), ("lever", "지레로 움직이다"), ("levy", "부과하다"),
    ("liberate", "해방하다"), ("license", "허가하다"), ("lick", "핥다"),
    ("lie", "눕다"), ("lift", "들어 올리다"), ("light", "불을 켜다"),
    ("lighten", "가볍게 하다"), ("like", "좋아하다"), ("limit", "제한하다"),
    ("limp", "절뚝거리다"), ("line", "줄을 서다"), ("linger", "머무르다"),
    ("link", "연결하다"), ("liquefy", "액화하다"), ("list", "나열하다"),
    ("listen", "듣다"), ("live", "살다"), ("load", "싣다"),
    ("loan", "대출하다"), ("lobby", "로비하다"), ("locate", "위치를 찾다"),
    ("lock", "잠그다"), ("lodge", "숙박하다"), ("log", "기록하다"),
    ("long", "갈망하다"), ("look", "보다"), ("loop", "반복하다"),
    ("loosen", "느슨하게 하다"), ("loot", "약탈하다"), ("lose", "잃다"),
    ("love", "사랑하다"), ("lower", "낮추다"), ("lubricate", "윤활하다"),
    ("lull", "달래다"), ("lure", "유인하다"), ("lurk", "잠복하다"),
]


def main() -> None:
    data = json.loads(PATH.read_text(encoding="utf-8"))
    have = {row["word"] for row in data["verbs"]}
    added = 0
    for en, ko in EXTRA:
        en = en.lower().strip()
        ko = ko.strip()
        if en in have or not WORD_RE.match(en):
            continue
        if not ko.endswith("다"):
            continue
        if not wn.synsets(en, pos="v"):
            continue
        data["verbs"].append({"word": en, "meaningKo": ko})
        have.add(en)
        added += 1
    PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"seed={len(data['verbs'])} added={added}")


if __name__ == "__main__":
    main()
